import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';

export const colors = {
  light: {
    primary: '#6366f1',
    primaryContainer: '#e0e7ff',
    secondary: '#4f46e5',
    secondaryContainer: '#e0e7ff',
    background: '#f8fafc',
    surface: '#ffffff',
    surfaceVariant: '#f1f5f9',
    surfaceCard: '#ffffff',
    border: '#e2e8f0',
    error: '#f43f5e',
    errorContainer: '#ffe4e6',
    success: '#10b981',
    successContainer: '#d1fae5',
    warning: '#f59e0b',
    warningContainer: '#fef3c7',
    info: '#0ea5e9',
    infoContainer: '#e0f2fe',
    text: '#0f172a',
    textSecondary: '#475569',
    textMuted: '#94a3b8',
    onPrimary: '#ffffff',
    onSecondary: '#ffffff',
    onBackground: '#0f172a',
    onSurface: '#0f172a',
    onSurfaceVariant: '#475569',
  },
  dark: {
    primary: '#818cf8',
    primaryContainer: '#312e81',
    secondary: '#6366f1',
    secondaryContainer: '#312e81',
    background: '#090d16',
    surface: '#131b2e',
    surfaceVariant: '#1e293b',
    surfaceCard: '#131b2e',
    border: '#1e293b',
    error: '#fb7185',
    errorContainer: '#4c0519',
    success: '#34d399',
    successContainer: '#064e3b',
    warning: '#fbbf24',
    warningContainer: '#78350f',
    info: '#38bdf8',
    infoContainer: '#0c4a6e',
    text: '#f8fafc',
    textSecondary: '#cbd5e1',
    textMuted: '#64748b',
    onPrimary: '#0f172a',
    onSecondary: '#0f172a',
    onBackground: '#f8fafc',
    onSurface: '#f8fafc',
    onSurfaceVariant: '#cbd5e1',
  },
};

// React Native Paper MD3 Themes Integration
export const paperLightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: colors.light.primary,
    onPrimary: colors.light.onPrimary,
    primaryContainer: colors.light.primaryContainer,
    secondary: colors.light.secondary,
    onSecondary: colors.light.onSecondary,
    secondaryContainer: colors.light.secondaryContainer,
    background: colors.light.background,
    surface: colors.light.surface,
    onSurface: colors.light.onSurface,
    surfaceVariant: colors.light.surfaceVariant,
    onSurfaceVariant: colors.light.onSurfaceVariant,
    error: colors.light.error,
    errorContainer: colors.light.errorContainer,
    outline: colors.light.border,
  },
};

export const paperDarkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: colors.dark.primary,
    onPrimary: colors.dark.onPrimary,
    primaryContainer: colors.dark.primaryContainer,
    secondary: colors.dark.secondary,
    onSecondary: colors.dark.onSecondary,
    secondaryContainer: colors.dark.secondaryContainer,
    background: colors.dark.background,
    surface: colors.dark.surface,
    onSurface: colors.dark.onSurface,
    surfaceVariant: colors.dark.surfaceVariant,
    onSurfaceVariant: colors.dark.onSurfaceVariant,
    error: colors.dark.error,
    errorContainer: colors.dark.errorContainer,
    outline: colors.dark.border,
  },
};
