/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/register-shop`; params?: Router.UnknownInputParams; } | { pathname: `/sales`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/customers` | `/customers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/ledger` | `/ledger`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/reports` | `/reports`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/customers/[customerId]`, params: Router.UnknownInputParams & { customerId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/register-shop`; params?: Router.UnknownOutputParams; } | { pathname: `/sales`; params?: Router.UnknownOutputParams; } | { pathname: `/signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/customers` | `/customers`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/ledger` | `/ledger`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/reports` | `/reports`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(dashboard)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/customers/[customerId]`, params: Router.UnknownOutputParams & { customerId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/explore${`?${string}` | `#${string}` | ''}` | `/forgot-password${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/register-shop${`?${string}` | `#${string}` | ''}` | `/sales${`?${string}` | `#${string}` | ''}` | `/signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/customers${`?${string}` | `#${string}` | ''}` | `/customers${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/ledger${`?${string}` | `#${string}` | ''}` | `/ledger${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/reports${`?${string}` | `#${string}` | ''}` | `/reports${`?${string}` | `#${string}` | ''}` | `${'/(dashboard)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/explore`; params?: Router.UnknownInputParams; } | { pathname: `/forgot-password`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/register-shop`; params?: Router.UnknownInputParams; } | { pathname: `/sales`; params?: Router.UnknownInputParams; } | { pathname: `/signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/customers` | `/customers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/ledger` | `/ledger`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/reports` | `/reports`; params?: Router.UnknownInputParams; } | { pathname: `${'/(dashboard)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | `/customers/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/customers/[customerId]`, params: Router.UnknownInputParams & { customerId: string | number; } };
    }
  }
}
